project_id = "fxgarugfgeeksiytslhr"

[functions.transfer-funds]
verify_jwt = false

[functions.process-referral]
verify_jwt = false

[functions.create-virtual-account]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.notify-admin-support]
verify_jwt = false
