
CREATE TABLE public.email_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  template_key text NOT NULL UNIQUE,
  template_name text NOT NULL,
  subject text NOT NULL DEFAULT '',
  html_content text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.email_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage email templates"
ON public.email_templates
FOR ALL
TO authenticated
USING (public.has_role(auth.uid(), 'admin'))
WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE TRIGGER update_email_templates_updated_at
  BEFORE UPDATE ON public.email_templates
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Insert default templates
INSERT INTO public.email_templates (template_key, template_name, subject, html_content) VALUES
('welcome', 'Welcome Email', 'Welcome to INKOTA SUB!', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;padding:0;background:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}table{border-spacing:0}.container{max-width:560px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.06)}.header{background:linear-gradient(135deg,#6C3AED,#8B5CF6);padding:40px 32px;text-align:center}.header h1{color:#fff;margin:0;font-size:24px;font-weight:700}.body{padding:32px}.body h2{margin:0 0 16px;font-size:20px;color:#1a1a1a}.body p{margin:0 0 16px;font-size:15px;line-height:1.6;color:#555}.btn{display:inline-block;padding:14px 32px;background:#6C3AED;color:#fff!important;text-decoration:none;border-radius:12px;font-weight:600;font-size:15px}.footer{padding:24px 32px;text-align:center;font-size:13px;color:#999;border-top:1px solid #f0f0f0}</style></head><body><div class="container"><div class="header"><h1>Welcome to INKOTA SUB 🎉</h1></div><div class="body"><h2>Hello there!</h2><p>We''re thrilled to have you join INKOTA SUB. Your account has been successfully created and you''re ready to start using our services.</p><p>With INKOTA SUB, you can purchase airtime, data bundles, pay utility bills, and much more — all from one platform.</p><a href="#" class="btn">Get Started</a><p style="margin-top:24px">If you have any questions, our support team is always here to help.</p></div><div class="footer">© 2025 INKOTA SUB. All rights reserved.</div></div></body></html>'),
('otp_verification', 'OTP / Verification Email', 'Your Verification Code', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;padding:0;background:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}.container{max-width:560px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.06)}.header{background:linear-gradient(135deg,#6C3AED,#8B5CF6);padding:40px 32px;text-align:center}.header h1{color:#fff;margin:0;font-size:24px;font-weight:700}.body{padding:32px}.body p{margin:0 0 16px;font-size:15px;line-height:1.6;color:#555}.otp-code{text-align:center;padding:24px;background:#f8f5ff;border-radius:12px;margin:24px 0}.otp-code span{font-size:36px;font-weight:700;letter-spacing:8px;color:#6C3AED}.footer{padding:24px 32px;text-align:center;font-size:13px;color:#999;border-top:1px solid #f0f0f0}</style></head><body><div class="container"><div class="header"><h1>Verification Code 🔐</h1></div><div class="body"><p>Hello,</p><p>Use the following code to verify your account. This code expires in 10 minutes.</p><div class="otp-code"><span>{{OTP_CODE}}</span></div><p>If you didn''t request this code, please ignore this email or contact support.</p></div><div class="footer">© 2025 INKOTA SUB. All rights reserved.</div></div></body></html>'),
('password_reset', 'Password Reset Email', 'Reset Your Password', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;padding:0;background:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}.container{max-width:560px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.06)}.header{background:linear-gradient(135deg,#6C3AED,#8B5CF6);padding:40px 32px;text-align:center}.header h1{color:#fff;margin:0;font-size:24px;font-weight:700}.body{padding:32px}.body p{margin:0 0 16px;font-size:15px;line-height:1.6;color:#555}.btn{display:inline-block;padding:14px 32px;background:#6C3AED;color:#fff!important;text-decoration:none;border-radius:12px;font-weight:600;font-size:15px}.footer{padding:24px 32px;text-align:center;font-size:13px;color:#999;border-top:1px solid #f0f0f0}</style></head><body><div class="container"><div class="header"><h1>Password Reset 🔑</h1></div><div class="body"><p>Hello,</p><p>We received a request to reset your password. Click the button below to create a new password.</p><a href="{{RESET_LINK}}" class="btn">Reset Password</a><p style="margin-top:24px">This link expires in 1 hour. If you didn''t request a password reset, you can safely ignore this email.</p></div><div class="footer">© 2025 INKOTA SUB. All rights reserved.</div></div></body></html>'),
('payment_receipt', 'Payment Receipt Email', 'Payment Confirmation', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;padding:0;background:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}.container{max-width:560px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.06)}.header{background:linear-gradient(135deg,#059669,#10B981);padding:40px 32px;text-align:center}.header h1{color:#fff;margin:0;font-size:24px;font-weight:700}.body{padding:32px}.body p{margin:0 0 16px;font-size:15px;line-height:1.6;color:#555}.receipt-table{width:100%;border-collapse:collapse;margin:20px 0}.receipt-table td{padding:12px 0;border-bottom:1px solid #f0f0f0;font-size:14px}.receipt-table td:first-child{color:#888}.receipt-table td:last-child{text-align:right;font-weight:600;color:#1a1a1a}.total td{border-bottom:none;font-size:18px}.total td:last-child{color:#059669}.footer{padding:24px 32px;text-align:center;font-size:13px;color:#999;border-top:1px solid #f0f0f0}</style></head><body><div class="container"><div class="header"><h1>Payment Confirmed ✅</h1></div><div class="body"><p>Hello,</p><p>Your payment has been successfully processed. Here are the details:</p><table class="receipt-table"><tr><td>Transaction ID</td><td>{{TRANSACTION_ID}}</td></tr><tr><td>Service</td><td>{{SERVICE}}</td></tr><tr><td>Date</td><td>{{DATE}}</td></tr><tr class="total"><td>Amount</td><td>₦{{AMOUNT}}</td></tr></table><p>Thank you for using INKOTA SUB!</p></div><div class="footer">© 2025 INKOTA SUB. All rights reserved.</div></div></body></html>'),
('subscription_confirmation', 'Subscription Confirmation Email', 'Subscription Confirmed', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;padding:0;background:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}.container{max-width:560px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.06)}.header{background:linear-gradient(135deg,#2563EB,#3B82F6);padding:40px 32px;text-align:center}.header h1{color:#fff;margin:0;font-size:24px;font-weight:700}.body{padding:32px}.body p{margin:0 0 16px;font-size:15px;line-height:1.6;color:#555}.plan-box{background:#eff6ff;border-radius:12px;padding:20px;margin:20px 0;text-align:center}.plan-box h3{margin:0 0 4px;color:#2563EB;font-size:20px}.plan-box p{margin:0;color:#666;font-size:14px}.btn{display:inline-block;padding:14px 32px;background:#2563EB;color:#fff!important;text-decoration:none;border-radius:12px;font-weight:600;font-size:15px}.footer{padding:24px 32px;text-align:center;font-size:13px;color:#999;border-top:1px solid #f0f0f0}</style></head><body><div class="container"><div class="header"><h1>Subscription Confirmed 🎉</h1></div><div class="body"><p>Hello,</p><p>Your subscription has been confirmed! Here are your plan details:</p><div class="plan-box"><h3>{{PLAN_NAME}}</h3><p>{{PLAN_DETAILS}}</p></div><p>Your subscription is now active. You can manage your subscription settings from your dashboard.</p><a href="#" class="btn">Go to Dashboard</a></div><div class="footer">© 2025 INKOTA SUB. All rights reserved.</div></div></body></html>');
